---
- name: Install Tomcat 9 on Ubuntu
hosts: app
become: true
tasks:
- name: Update apt cache
apt:
update_cache: yes


- name: Install Java and Tomcat
apt:
name:
- default-jdk-headless
- tomcat9
- tomcat9-admin
state: present


- name: Ensure Tomcat is enabled and running
service:
name: tomcat9
state: started
enabled: yes
